name: Update Lead Tags

on:
  schedule:
    # Exécution tous les jours à minuit
    - cron: '0 0 * * *'
  workflow_dispatch:  # Permet d'exécuter manuellement ce workflow

jobs:
  update-tags:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz

    - name: Run script
      run: |
        python tag.py
